[package]
name = "demo_monitor_route_with_kernel_filter"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
libc = "0.2.153"
netlink-sys = "0.8.5"
rtnetlink = "0.14.1"
tokio = { version = "1.36.0", features = ["rt", "macros", "net", "rt-multi-thread"] }
